
export const defaultNoteJournalier = {
  id: 0,
  note_Maths: 0,
  coef_Maths: 0,
  note_Pc: 0,
  coef_Pc: 0,
  note_Ang: 0,
  coef_Ang: 0,
  note_Mal: 0,
  coef_Mal: 0,
  note_Fr: 0,
  coef_Fr: 0,
  note_Philo: 0,
  coef_Philo: 0,
  note_HistoGeo: 0,
  coef_HistoGeo: 0,
  note_SVT: 0,
  coef_SVT: 0,
  note_Eps: 0,
  coef_Eps: 0,

}

export const defaultNoteComposition = {
  id: 0,
  note_Maths: 0,
  coef_Maths: 0,
  note_Pc: 0,
  coef_Pc: 0,
  note_Ang: 0,
  coef_Ang: 0,
  note_Mal: 0,
  coef_Mal: 0,
  note_Fr: 0,
  coef_Fr: 0,
  note_Philo: 0,
  coef_Philo: 0,
  note_HistoGeo: 0,
  coef_HistoGeo: 0,
  note_SVT: 0,
  coef_SVT: 0,
  note_Eps: 0,
  coef_Eps: 0,
}
